import type { DashboardLocale, InteractionTrigger, MascotSettings } from "./types";
const STORAGE_KEY = "nightlight-mascot-settings";
const SETTINGS_SCHEMA_VERSION = 5;
const UI_STORAGE_KEY = "desktop-mascot-dashboard-preferences";
const AUTHOR_DATA_CACHE_KEY = "desktop-mascot-author-data";
const AUTHOR_DATA_URL = "https://raw.githubusercontent.com/jingluoguo/jingluo_web/master/author.json";
const DEFAULT_SETTINGS: MascotSettings = {
  character: "ghost",
  emotion: "02",
  size: 120,
  viewMode: "3d",
  outlineVisible: true,
  followCursor: true,
  edgeDock: false,
  edgeDockThreshold: 20,
  bodyColor: "#bdeef2",
  outlineColor: "#23434d",
  accentColor: "#a9d9ff",
  globalShortcut: "CommandOrControl+Shift+M",
  dashboardShortcut: "CommandOrControl+Shift+D",
  faceVariant: "default",
  accessories: {},
  interactions: {
    click: "10",
    doubleClick: "16",
    hover: "11",
    drag: "38",
  },
};
const interactionTriggers: Array<{ id: InteractionTrigger; defaultEmotion: string }> = [
  { id: "click", defaultEmotion: "10" },
  { id: "doubleClick", defaultEmotion: "16" },
  { id: "hover", defaultEmotion: "11" },
  { id: "drag", defaultEmotion: "38" },
];
const MAX_MASCOT_SIZE = 160;
const CONTEXT_MENU_WIDTH = 220;

const characters = [
  { id: "ghost", name: { "zh-CN": "幽灵", en: "Ghost" }, symbol: "G" },
  { id: "sprout", name: { "zh-CN": "豆芽", en: "Sprout" }, symbol: "S" },
  { id: "cat", name: { "zh-CN": "猫咪", en: "Cat" }, symbol: "C" },
  { id: "robot", name: { "zh-CN": "机器人", en: "Robot" }, symbol: "R" },
  { id: "jelly", name: { "zh-CN": "果冻", en: "Jelly" }, symbol: "J" },
];

const uiText = {
  "zh-CN": {
    dashboardLabel: "仪表盘",
    hidePet: "隐藏",
    quitApp: "退出",
    subtitle: "让每一刻，都有一个轻盈的陪伴。",
    appearanceTab: "角色与外观",
    behaviorTab: "行为与快捷键",
    focusTab: "专注与番茄钟",
    remindersTab: "定时提醒",
    emotionsTab: "表情",
    aboutTab: "关于作者",
    appearanceEyebrow: "外观",
    behaviorEyebrow: "偏好",
    emotionsEyebrow: "状态",
    aboutEyebrow: "关于",
    characterModel: "角色模型",
    behavior: "行为与外观",
    reset: "恢复默认",
    size: "模型大小",
    viewMode: "显示模式",
    followCursor: "鼠标跟随",
    followHint: "失去焦点时仍会感知系统鼠标位置",
    edgeDock: "边缘吸附",
    edgeDockHint: "松开拖拽后靠近屏幕边缘时自动收起；提醒会自动弹出",
    edgeDockThreshold: "吸附范围",
    interactions: "互动反应",
    interactionsHint: "为点击、双击、悬停和拖拽设置反应。模型未声明的反应会自动跳过。",
    interactionClick: "点击",
    interactionClickHint: "轻点宠物时触发",
    interactionDoubleClick: "双击",
    interactionDoubleClickHint: "连续轻点两次时触发",
    interactionHover: "悬停",
    interactionHoverHint: "鼠标进入宠物时触发",
    interactionDrag: "拖拽",
    interactionDragHint: "拖动宠物后松开时触发",
    interactionNone: "不触发反应",
    interactionUnavailable: "当前模型未声明此反应，将保持当前状态",
    quickInteractions: "快捷反应",
    scrollQuickReactions: "滚动快捷反应",
    scrollLeft: "向左滚动",
    scrollRight: "向右滚动",
    quickHappy: "开心",
    quickCurious: "好奇",
    quickLove: "心动",
    toggleAccessory: "切换配件",
    outline: "模型轮廓",
    outlineHint: "显示角色外侧描边",
    bodyColor: "主体",
    outlineColor: "轮廓",
    accentColor: "强调",
    emotions: "表情状态",
    emotionCount: "种",
    setEmotion: "设置表情",
    emotionApplied: "已应用到桌面宠物",
    idle: "待机",
    light: "白天",
    dark: "黑夜",
    language: "语言",
    theme: "主题",
    aboutAuthor: "关于作者",
    authorWorks: "作品",
    featuredWork: "精选",
    workVersion: "版本",
    releasedAt: "发布于",
    authorLoading: "正在读取作者资料…",
    authorUnavailable: "暂时无法读取作者资料",
    authorCached: "当前显示上次成功加载的数据",
    retry: "重试",
    dataUpdatedAt: "资料更新",
    globalShortcut: "显示或隐藏",
    globalShortcutHint: "按下后显示或隐藏桌面宠物",
    dashboardShortcut: "打开仪表盘",
    dashboardShortcutHint: "按下后打开并聚焦仪表盘",
    remindersTitle: "定时任务",
    remindersHint: "有启用任务时，后台每秒检查一次；没有任务时自动停止。",
    addReminder: "新增提醒",
    editReminder: "编辑提醒",
    reminderTitle: "提醒内容",
    reminderTime: "首次时间",
    reminderDate: "日期",
    reminderClock: "时间",
    reminderSchedule: "重复方式",
    once: "仅一次",
    daily: "每天",
    weekdays: "工作日",
    interval: "按间隔",
    intervalMinutes: "间隔分钟",
    reminderEmotion: "触发表情",
    saveReminder: "保存任务",
    cancelReminder: "取消编辑",
    noReminders: "还没有定时任务",
    reminderEnabled: "已启用",
    strongReminder: "强提醒",
    strongReminderHint: "保持弹出，直到点击宠物后再自动归位",
    nextReminder: "下次提醒",
    deleteReminder: "删除",
    reminderSaved: "提醒已保存",
    reminderRoutines: "我的提醒",
    reminderOn: "启用",
    reminderOff: "停用",
    reminderPaused: "已暂停",
    focusTitle: "开始新一轮",
    focusHint: "写下这一轮要做的事，设定时长后直接开始。",
    focusMode: "专注模式",
    focusSession: "专注",
    shortBreak: "短休息",
    longBreak: "长休息",
    startFocus: "开始",
    pauseFocus: "暂停",
    resumeFocus: "继续",
    resetFocus: "重置",
    skipFocus: "跳过阶段",
    focusToday: "今日完成专注",
    focusDuration: "专注时长",
    shortBreakDuration: "短休息时长",
    longBreakDuration: "长休息时长",
    longBreakEvery: "长休息间隔",
    cycles: "个专注周期后",
    focusRunning: "进行中",
    focusPaused: "已暂停",
    focusReady: "准备开始",
    petReminderLabel: "提醒",
    petAriaLabel: "可拖拽的桌面宠物",
    pomodoroBreakStarted: "专注完成，休息一下吧",
    pomodoroFocusStarted: "休息结束，准备继续专注",
    session: "本轮",
    sessionTitle: "这一轮要做什么",
    sessionTitlePlaceholder: "例如：整理项目方案",
    sessionType: "类型",
    sessionDuration: "本轮时长",
    minutes: "分钟",
    startTimer: "开始倒计时",
    resetTimer: "重新设定",
    sessionLocked: "本轮进行中，重置后可重新设定。",
    autostart: "登录时启动",
    autostartHint: "系统登录后自动启动 Desktop Mascot",
    autostartEnabled: "启动项已启用",
    autostartDisabled: "启动项未启用",
    autostartUnavailable: "无法检查启动项权限",
    autostartEnable: "请求启动项权限",
    autostartDisable: "停用启动项",
    autostartRefresh: "重新检查",
    appUpdate: "应用更新",
    appUpdateHint: "自动下载可用更新；下载完成后可在此安装。",
    checkForUpdate: "检查更新",
    updateNotChecked: "尚未检查更新",
    checkingForUpdate: "正在检查更新…",
    updateAvailable: "发现新版本",
    updateDownloading: "正在下载更新",
    updatePaused: "下载已暂停",
    updateReady: "更新已下载完成",
    upToDate: "已是最新版本",
    updateFailed: "无法检查或下载更新",
    pauseUpdate: "暂停下载",
    resumeUpdate: "继续下载",
    downloadUpdate: "下载更新",
    installUpdate: "安装更新",
    installingUpdate: "正在安装更新…",
    updatePausedHint: "继续下载时会重新开始。",
    updateReadyHint: "安装后应用将重新启动。",
    recordShortcut: "录制快捷键",
    recordingShortcut: "请按下快捷键…",
    shortcutConflict: "该快捷键已被占用，请尝试其他组合",
    importModel: "导入模型",
    modelTrustHint: "模型脚本将在本地应用窗口中运行，请仅导入来自 lively-mascot Skill 的文件。",
    modelImported: "模型已导入",
    modelExported: "模型包已导出",
    modelImportError: "模型导入失败",
    modelFormatHint: "支持 .livelymodel（ZIP 格式），或同时选择 model.js、model.css、model.json。文件应来自 ",
    dropModel: "拖放模型文件到这里",
    chooseModel: "选择模型文件",
    modelPackageContents: "模型包应包含 model.js、model.css 和 model.json。",
    deleteModel: "删除模型",
    exportModel: "导出模型",
    deleteModelConfirm: "确定删除这个用户模型吗？删除后可重新导入，但无法恢复当前副本。",
    exportModelConfirm: "确定导出这个用户模型吗？将下载一个 .livelymodel 文件。",
    confirmModelAction: "确认操作",
    confirm: "确认",
    cancel: "取消",
    modelDeleted: "模型已删除",
    userModel: "用户模型",
    officialModel: "内置模型",
    modelCapabilities: "模型能力",
    modelParts: "部件",
    modelGaze: "注视",
    modelMotion: "动作",
    modelAccessories: "配件",
    faceVariant: "脸型",
    faceDefault: "默认",
    faceSimple: "简洁",
    faceDot: "点状",
    noAccessories: "当前模型没有可切换配件",
    modelImportInvalid: "无法读取模型。请确认模型包包含完整文件，并由 lively-mascot Skill 生成。",
    modelImportUnsupported: "模型包版本不受支持。请使用 lively-mascot 0.3.1 生成模型。",
    modelImportTooLarge: "模型文件超过 2 MB 限制，请压缩资源后重试。",
    modelImportUnsafe: "模型包含不允许的网络、动态代码或应用接口调用。",
  },
  en: {
    dashboardLabel: "Dashboard",
    hidePet: "Hide",
    quitApp: "Quit",
    subtitle: "A little companion for every moment.",
    appearanceTab: "Character & Style",
    behaviorTab: "Behavior & Shortcuts",
    focusTab: "Focus & Pomodoro",
    remindersTab: "Reminders",
    emotionsTab: "Expressions",
    aboutTab: "About the Author",
    appearanceEyebrow: "Appearance",
    behaviorEyebrow: "Preferences",
    emotionsEyebrow: "State",
    aboutEyebrow: "About",
    characterModel: "Character",
    behavior: "Behavior & Appearance",
    reset: "Reset",
    size: "Mascot size",
    viewMode: "View mode",
    followCursor: "Follow cursor",
    followHint: "Tracks the system cursor even when unfocused",
    edgeDock: "Edge dock",
    edgeDockHint: "Dock near a screen edge after dragging; reminders reveal it automatically",
    edgeDockThreshold: "Snap range",
    interactions: "Interaction responses",
    interactionsHint: "Choose reactions for click, double click, hover, and drag. Reactions not declared by a model are safely skipped.",
    interactionClick: "Click",
    interactionClickHint: "Triggers when the mascot is clicked",
    interactionDoubleClick: "Double click",
    interactionDoubleClickHint: "Triggers when the mascot is clicked twice",
    interactionHover: "Hover",
    interactionHoverHint: "Triggers when the pointer enters the mascot",
    interactionDrag: "Drag",
    interactionDragHint: "Triggers when the mascot is dropped",
    interactionNone: "No reaction",
    interactionUnavailable: "This model has not declared this reaction; the current state is kept",
    quickInteractions: "Quick reactions",
    scrollQuickReactions: "Scroll quick reactions",
    scrollLeft: "Scroll left",
    scrollRight: "Scroll right",
    quickHappy: "Happy",
    quickCurious: "Curious",
    quickLove: "Love",
    toggleAccessory: "Toggle accessory",
    outline: "Character outline",
    outlineHint: "Show the outline around the character",
    bodyColor: "Body",
    outlineColor: "Outline",
    accentColor: "Accent",
    emotions: "Expressions",
    emotionCount: "total",
    setEmotion: "Set expression",
    emotionApplied: "Applied to desktop mascot",
    idle: "Idle",
    light: "Light",
    dark: "Dark",
    language: "Language",
    theme: "Theme",
    aboutAuthor: "About the author",
    authorWorks: "Selected work",
    featuredWork: "Featured",
    workVersion: "Version",
    releasedAt: "Released",
    authorLoading: "Loading author profile…",
    authorUnavailable: "The author profile is currently unavailable",
    authorCached: "Showing the last successfully loaded data",
    retry: "Retry",
    dataUpdatedAt: "Data updated",
    globalShortcut: "Show or hide",
    globalShortcutHint: "Show or hide the desktop mascot",
    dashboardShortcut: "Open dashboard",
    dashboardShortcutHint: "Open and focus the dashboard",
    remindersTitle: "Scheduled tasks",
    remindersHint: "The background checks every second only while a task is enabled.",
    addReminder: "Add reminder",
    editReminder: "Edit reminder",
    reminderTitle: "Reminder text",
    reminderTime: "First time",
    reminderDate: "Date",
    reminderClock: "Time",
    reminderSchedule: "Repeat",
    once: "Once",
    daily: "Daily",
    weekdays: "Weekdays",
    interval: "Interval",
    intervalMinutes: "Interval minutes",
    reminderEmotion: "Trigger emotion",
    saveReminder: "Save task",
    cancelReminder: "Cancel edit",
    noReminders: "No scheduled tasks yet",
    reminderEnabled: "Enabled",
    strongReminder: "Persistent reminder",
    strongReminderHint: "Stay revealed until the mascot is clicked, then dock automatically",
    nextReminder: "Next reminder",
    deleteReminder: "Delete",
    reminderSaved: "Reminder saved",
    reminderRoutines: "YOUR ROUTINES",
    reminderOn: "ON",
    reminderOff: "OFF",
    reminderPaused: "PAUSED",
    focusTitle: "Start a session",
    focusHint: "Name what you are doing, set the time, and start when ready.",
    focusMode: "FOCUS MODE",
    focusSession: "Focus",
    shortBreak: "Short break",
    longBreak: "Long break",
    startFocus: "Start",
    pauseFocus: "Pause",
    resumeFocus: "Resume",
    resetFocus: "Reset",
    skipFocus: "Skip phase",
    focusToday: "Focus sessions today",
    focusDuration: "Focus duration",
    shortBreakDuration: "Short break duration",
    longBreakDuration: "Long break duration",
    longBreakEvery: "Long break after",
    cycles: "focus cycles",
    focusRunning: "Running",
    focusPaused: "Paused",
    focusReady: "Ready",
    petReminderLabel: "Reminder",
    petAriaLabel: "Draggable desktop mascot",
    pomodoroBreakStarted: "Time for a break",
    pomodoroFocusStarted: "Ready to focus again",
    session: "SESSION",
    sessionTitle: "What are you doing?",
    sessionTitlePlaceholder: "For example: Draft the project plan",
    sessionType: "Type",
    sessionDuration: "Duration",
    minutes: "minutes",
    startTimer: "Start timer",
    resetTimer: "Set again",
    sessionLocked: "This session is in progress. Reset it to make changes.",
    autostart: "Launch at login",
    autostartHint: "Start Desktop Mascot automatically when you sign in",
    autostartEnabled: "Launch at login is enabled",
    autostartDisabled: "Launch at login is disabled",
    autostartUnavailable: "Unable to check login-item permission",
    autostartEnable: "Request login-item access",
    autostartDisable: "Disable launch at login",
    autostartRefresh: "Check again",
    appUpdate: "App updates",
    appUpdateHint: "Available updates download automatically and can be installed here.",
    checkForUpdate: "Check for updates",
    updateNotChecked: "Updates haven't been checked",
    checkingForUpdate: "Checking for updates…",
    updateAvailable: "Update available",
    updateDownloading: "Downloading update",
    updatePaused: "Download paused",
    updateReady: "Update downloaded",
    upToDate: "You're up to date",
    updateFailed: "Unable to check for or download updates",
    pauseUpdate: "Pause download",
    resumeUpdate: "Resume download",
    downloadUpdate: "Download update",
    installUpdate: "Install update",
    installingUpdate: "Installing update…",
    updatePausedHint: "Resuming starts the download again.",
    updateReadyHint: "The app will restart to install the update.",
    recordShortcut: "Record shortcut",
    recordingShortcut: "Press a shortcut…",
    shortcutConflict: "This shortcut is already in use. Try another combination.",
    importModel: "Import model",
    modelTrustHint: "Model scripts run in this app window. Import files only from the lively-mascot Skill.",
    modelImported: "Model imported",
    modelExported: "Model package exported",
    modelImportError: "Model import failed",
    modelFormatHint: "Supports .livelymodel (ZIP), or model.js, model.css, and model.json selected together. Files should come from the ",
    dropModel: "Drop model files here",
    chooseModel: "Choose model files",
    modelPackageContents: "A model package must contain model.js, model.css, and model.json.",
    deleteModel: "Delete model",
    exportModel: "Export model",
    deleteModelConfirm: "Delete this user model? You can import it again, but this copy cannot be restored.",
    exportModelConfirm: "Export this user model? A .livelymodel package will be downloaded.",
    confirmModelAction: "Confirm action",
    confirm: "Confirm",
    cancel: "Cancel",
    modelDeleted: "Model deleted",
    userModel: "User model",
    officialModel: "Built-in model",
    modelCapabilities: "Model capabilities",
    modelParts: "Parts",
    modelGaze: "Gaze",
    modelMotion: "Motion",
    modelAccessories: "Accessories",
    faceVariant: "Face",
    faceDefault: "Default",
    faceSimple: "Simple",
    faceDot: "Dot",
    noAccessories: "This model has no switchable accessories",
    modelImportInvalid: "The model could not be read. Confirm that the package is complete and was generated by the lively-mascot Skill.",
    modelImportUnsupported: "This model package version is not supported. Generate the model with lively-mascot 0.3.1.",
    modelImportTooLarge: "A model file exceeds the 2 MB limit. Reduce its size and try again.",
    modelImportUnsafe: "The model contains a blocked network, dynamic-code, or app-interface call.",
  },
} as const;

type UiCopy = { [Key in keyof typeof uiText["zh-CN"]]: string };

const englishEmotionGroups: Record<string, string> = {
  lifecycle: "Lifecycle",
  reaction: "Reactions",
  work: "Work states",
};

const workTypeName = (type: string, locale: DashboardLocale) => {
  const normalized = type.trim().toLowerCase();
  if (locale === "zh-CN") return ({ app: "应用", plugin: "插件", web: "网站", library: "库" } as Record<string, string>)[normalized] ?? type;
  return ({ app: "App", plugin: "Plugin", web: "Web", library: "Library" } as Record<string, string>)[normalized] ?? type;
};
const workTypeClass = (type: string) => type.trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-");

const defaultThemes: Record<string, Pick<MascotSettings, "bodyColor" | "outlineColor" | "accentColor">> = {
  sprout: { bodyColor: "#48ff42", outlineColor: "#080808", accentColor: "#ff9fb6" },
  cat: { bodyColor: "#3d4852", outlineColor: "#131a20", accentColor: "#eeb3c1" },
  robot: { bodyColor: "#6f879b", outlineColor: "#162332", accentColor: "#74e5ff" },
  ghost: { bodyColor: "#bdeef2", outlineColor: "#23434d", accentColor: "#a9d9ff" },
  jelly: { bodyColor: "#f29cc2", outlineColor: "#5a243e", accentColor: "#ffe0a8" },
};
export { STORAGE_KEY, SETTINGS_SCHEMA_VERSION, UI_STORAGE_KEY, AUTHOR_DATA_CACHE_KEY, AUTHOR_DATA_URL, DEFAULT_SETTINGS, MAX_MASCOT_SIZE, CONTEXT_MENU_WIDTH, interactionTriggers, characters, uiText, englishEmotionGroups, workTypeName, workTypeClass, defaultThemes };
export type { UiCopy };
