import type { DashboardLocale, MascotSettings } from "./types";
const STORAGE_KEY = "nightlight-mascot-settings";
const SETTINGS_SCHEMA_VERSION = 2;
const UI_STORAGE_KEY = "desktop-mascot-dashboard-preferences";
const AUTHOR_DATA_CACHE_KEY = "desktop-mascot-author-data";
const AUTHOR_DATA_URL = "https://raw.githubusercontent.com/jingluoguo/jingluo_web/master/author.json";
const DEFAULT_SETTINGS: MascotSettings = {
  character: "ghost",
  emotion: "02",
  size: 120,
  viewMode: "3d",
  outlineVisible: true,
  followCursor: true,
  bodyColor: "#bdeef2",
  outlineColor: "#23434d",
  accentColor: "#a9d9ff",
  globalShortcut: "CommandOrControl+Shift+M",
  dashboardShortcut: "CommandOrControl+Shift+D",
  faceVariant: "default",
  accessories: {},
};
const MAX_MASCOT_SIZE = 160;

const characters = [
  { id: "ghost", name: { "zh-CN": "幽灵", en: "Ghost" }, symbol: "G" },
  { id: "sprout", name: { "zh-CN": "豆芽", en: "Sprout" }, symbol: "S" },
  { id: "cat", name: { "zh-CN": "猫咪", en: "Cat" }, symbol: "C" },
  { id: "robot", name: { "zh-CN": "机器人", en: "Robot" }, symbol: "R" },
  { id: "jelly", name: { "zh-CN": "果冻", en: "Jelly" }, symbol: "J" },
];

const uiText = {
  "zh-CN": {
    dashboardLabel: "仪表盘",
    subtitle: "让每一刻，都有一个轻盈的陪伴。",
    appearanceTab: "角色与外观",
    behaviorTab: "行为与快捷键",
    emotionsTab: "表情",
    aboutTab: "关于作者",
    appearanceEyebrow: "外观",
    behaviorEyebrow: "偏好",
    emotionsEyebrow: "状态",
    aboutEyebrow: "关于",
    characterModel: "角色模型",
    behavior: "行为与外观",
    reset: "恢复默认",
    size: "模型大小",
    viewMode: "显示模式",
    followCursor: "鼠标跟随",
    followHint: "失去焦点时仍会感知系统鼠标位置",
    outline: "模型轮廓",
    outlineHint: "显示角色外侧描边",
    bodyColor: "主体",
    outlineColor: "轮廓",
    accentColor: "强调",
    emotions: "表情状态",
    emotionCount: "种",
    setEmotion: "设置表情",
    emotionApplied: "已应用到桌面宠物",
    idle: "待机",
    light: "白天",
    dark: "黑夜",
    language: "语言",
    theme: "主题",
    aboutAuthor: "关于作者",
    authorWorks: "作品",
    featuredWork: "精选",
    workVersion: "版本",
    releasedAt: "发布于",
    authorLoading: "正在读取作者资料…",
    authorUnavailable: "暂时无法读取作者资料",
    authorCached: "当前显示上次成功加载的数据",
    retry: "重试",
    dataUpdatedAt: "资料更新",
    globalShortcut: "显示或隐藏",
    globalShortcutHint: "按下后显示或隐藏桌面宠物",
    dashboardShortcut: "打开仪表盘",
    dashboardShortcutHint: "按下后打开并聚焦仪表盘",
    autostart: "登录时启动",
    autostartHint: "系统登录后自动启动 Desktop Mascot",
    autostartEnabled: "启动项已启用",
    autostartDisabled: "启动项未启用",
    autostartUnavailable: "无法检查启动项权限",
    autostartEnable: "请求启动项权限",
    autostartDisable: "停用启动项",
    autostartRefresh: "重新检查",
    appUpdate: "应用更新",
    appUpdateHint: "自动下载可用更新；下载完成后可在此安装。",
    checkForUpdate: "检查更新",
    updateNotChecked: "尚未检查更新",
    checkingForUpdate: "正在检查更新…",
    updateAvailable: "发现新版本",
    updateDownloading: "正在下载更新",
    updatePaused: "下载已暂停",
    updateReady: "更新已下载完成",
    upToDate: "已是最新版本",
    updateFailed: "无法检查或下载更新",
    pauseUpdate: "暂停下载",
    resumeUpdate: "继续下载",
    downloadUpdate: "下载更新",
    installUpdate: "安装更新",
    installingUpdate: "正在安装更新…",
    updatePausedHint: "继续下载时会重新开始。",
    updateReadyHint: "安装后应用将重新启动。",
    recordShortcut: "录制快捷键",
    recordingShortcut: "请按下快捷键…",
    shortcutConflict: "该快捷键已被占用，请尝试其他组合",
    importModel: "导入模型",
    modelTrustHint: "模型脚本将在本地应用窗口中运行，请仅导入来自 lively-mascot Skill 的文件。",
    modelImported: "模型已导入",
    modelExported: "模型包已导出",
    modelImportError: "模型导入失败",
    modelFormatHint: "支持 .livelymodel（ZIP 格式），或同时选择 model.js、model.css、model.json。文件应来自 ",
    dropModel: "拖放模型文件到这里",
    chooseModel: "选择模型文件",
    modelPackageContents: "模型包应包含 model.js、model.css 和 model.json。",
    deleteModel: "删除模型",
    exportModel: "导出模型",
    deleteModelConfirm: "确定删除这个用户模型吗？删除后可重新导入，但无法恢复当前副本。",
    exportModelConfirm: "确定导出这个用户模型吗？将下载一个 .livelymodel 文件。",
    confirmModelAction: "确认操作",
    confirm: "确认",
    cancel: "取消",
    modelDeleted: "模型已删除",
    userModel: "用户模型",
    officialModel: "内置模型",
    modelCapabilities: "模型能力",
    modelParts: "部件",
    modelGaze: "注视",
    modelMotion: "动作",
    modelAccessories: "配件",
    faceVariant: "脸型",
    faceDefault: "默认",
    faceSimple: "简洁",
    faceDot: "点状",
    noAccessories: "当前模型没有可切换配件",
    modelImportInvalid: "无法读取模型。请确认模型包包含完整文件，并由 lively-mascot Skill 生成。",
    modelImportUnsupported: "模型包版本不受支持。请使用 lively-mascot 0.3.1 生成模型。",
    modelImportTooLarge: "模型文件超过 2 MB 限制，请压缩资源后重试。",
    modelImportUnsafe: "模型包含不允许的网络、动态代码或应用接口调用。",
  },
  en: {
    dashboardLabel: "Dashboard",
    subtitle: "A little companion for every moment.",
    appearanceTab: "Character & Style",
    behaviorTab: "Behavior & Shortcuts",
    emotionsTab: "Expressions",
    aboutTab: "About the Author",
    appearanceEyebrow: "Appearance",
    behaviorEyebrow: "Preferences",
    emotionsEyebrow: "State",
    aboutEyebrow: "About",
    characterModel: "Character",
    behavior: "Behavior & Appearance",
    reset: "Reset",
    size: "Mascot size",
    viewMode: "View mode",
    followCursor: "Follow cursor",
    followHint: "Tracks the system cursor even when unfocused",
    outline: "Character outline",
    outlineHint: "Show the outline around the character",
    bodyColor: "Body",
    outlineColor: "Outline",
    accentColor: "Accent",
    emotions: "Expressions",
    emotionCount: "total",
    setEmotion: "Set expression",
    emotionApplied: "Applied to desktop mascot",
    idle: "Idle",
    light: "Light",
    dark: "Dark",
    language: "Language",
    theme: "Theme",
    aboutAuthor: "About the author",
    authorWorks: "Selected work",
    featuredWork: "Featured",
    workVersion: "Version",
    releasedAt: "Released",
    authorLoading: "Loading author profile…",
    authorUnavailable: "The author profile is currently unavailable",
    authorCached: "Showing the last successfully loaded data",
    retry: "Retry",
    dataUpdatedAt: "Data updated",
    globalShortcut: "Show or hide",
    globalShortcutHint: "Show or hide the desktop mascot",
    dashboardShortcut: "Open dashboard",
    dashboardShortcutHint: "Open and focus the dashboard",
    autostart: "Launch at login",
    autostartHint: "Start Desktop Mascot automatically when you sign in",
    autostartEnabled: "Launch at login is enabled",
    autostartDisabled: "Launch at login is disabled",
    autostartUnavailable: "Unable to check login-item permission",
    autostartEnable: "Request login-item access",
    autostartDisable: "Disable launch at login",
    autostartRefresh: "Check again",
    appUpdate: "App updates",
    appUpdateHint: "Available updates download automatically and can be installed here.",
    checkForUpdate: "Check for updates",
    updateNotChecked: "Updates haven't been checked",
    checkingForUpdate: "Checking for updates…",
    updateAvailable: "Update available",
    updateDownloading: "Downloading update",
    updatePaused: "Download paused",
    updateReady: "Update downloaded",
    upToDate: "You're up to date",
    updateFailed: "Unable to check for or download updates",
    pauseUpdate: "Pause download",
    resumeUpdate: "Resume download",
    downloadUpdate: "Download update",
    installUpdate: "Install update",
    installingUpdate: "Installing update…",
    updatePausedHint: "Resuming starts the download again.",
    updateReadyHint: "The app will restart to install the update.",
    recordShortcut: "Record shortcut",
    recordingShortcut: "Press a shortcut…",
    shortcutConflict: "This shortcut is already in use. Try another combination.",
    importModel: "Import model",
    modelTrustHint: "Model scripts run in this app window. Import files only from the lively-mascot Skill.",
    modelImported: "Model imported",
    modelExported: "Model package exported",
    modelImportError: "Model import failed",
    modelFormatHint: "Supports .livelymodel (ZIP), or model.js, model.css, and model.json selected together. Files should come from the ",
    dropModel: "Drop model files here",
    chooseModel: "Choose model files",
    modelPackageContents: "A model package must contain model.js, model.css, and model.json.",
    deleteModel: "Delete model",
    exportModel: "Export model",
    deleteModelConfirm: "Delete this user model? You can import it again, but this copy cannot be restored.",
    exportModelConfirm: "Export this user model? A .livelymodel package will be downloaded.",
    confirmModelAction: "Confirm action",
    confirm: "Confirm",
    cancel: "Cancel",
    modelDeleted: "Model deleted",
    userModel: "User model",
    officialModel: "Built-in model",
    modelCapabilities: "Model capabilities",
    modelParts: "Parts",
    modelGaze: "Gaze",
    modelMotion: "Motion",
    modelAccessories: "Accessories",
    faceVariant: "Face",
    faceDefault: "Default",
    faceSimple: "Simple",
    faceDot: "Dot",
    noAccessories: "This model has no switchable accessories",
    modelImportInvalid: "The model could not be read. Confirm that the package is complete and was generated by the lively-mascot Skill.",
    modelImportUnsupported: "This model package version is not supported. Generate the model with lively-mascot 0.3.1.",
    modelImportTooLarge: "A model file exceeds the 2 MB limit. Reduce its size and try again.",
    modelImportUnsafe: "The model contains a blocked network, dynamic-code, or app-interface call.",
  },
} as const;

type UiCopy = { [Key in keyof typeof uiText["zh-CN"]]: string };

const englishEmotionGroups: Record<string, string> = {
  lifecycle: "Lifecycle",
  reaction: "Reactions",
  work: "Work states",
};

const workTypeName = (type: string, locale: DashboardLocale) => {
  const normalized = type.trim().toLowerCase();
  if (locale === "zh-CN") return ({ app: "应用", plugin: "插件", web: "网站", library: "库" } as Record<string, string>)[normalized] ?? type;
  return ({ app: "App", plugin: "Plugin", web: "Web", library: "Library" } as Record<string, string>)[normalized] ?? type;
};
const workTypeClass = (type: string) => type.trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-");

const defaultThemes: Record<string, Pick<MascotSettings, "bodyColor" | "outlineColor" | "accentColor">> = {
  sprout: { bodyColor: "#48ff42", outlineColor: "#080808", accentColor: "#ff9fb6" },
  cat: { bodyColor: "#3d4852", outlineColor: "#131a20", accentColor: "#eeb3c1" },
  robot: { bodyColor: "#6f879b", outlineColor: "#162332", accentColor: "#74e5ff" },
  ghost: { bodyColor: "#bdeef2", outlineColor: "#23434d", accentColor: "#a9d9ff" },
  jelly: { bodyColor: "#f29cc2", outlineColor: "#5a243e", accentColor: "#ffe0a8" },
};
export { STORAGE_KEY, SETTINGS_SCHEMA_VERSION, UI_STORAGE_KEY, AUTHOR_DATA_CACHE_KEY, AUTHOR_DATA_URL, DEFAULT_SETTINGS, MAX_MASCOT_SIZE, characters, uiText, englishEmotionGroups, workTypeName, workTypeClass, defaultThemes };
export type { UiCopy };
